name: Deploy Production 🚀

on:
  release:
    types: 
      - published
      - edited

jobs:
  deploy-to-production:
    name: Deploy to production server 🚀
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Step 1: Checkout repository
      - name: Execute deployment command
        uses: actions/checkout@v3

      # Step 2: Deploy to production server via SSH
      - name: Deploy to production server
        uses: appleboy/ssh-action@v0.1.10
        env:
          APP_PROD_PATH: ${{ vars.APP_PROD_PATH }}
          GIT_URL: ${{ secrets.GIT_URL }}
          MINIO_PROD_ENDPOINT: ${{ secrets.MINIO_PROD_ENDPOINT }}
          MINIO_PROD_ACCESS_KEY: ${{ secrets.MINIO_PROD_ACCESS_KEY }}
          MINIO_PROD_SECRET_KEY: ${{ secrets.MINIO_PROD_SECRET_KEY }}
          APP_PROD_PORT: ${{ secrets.APP_PROD_PORT }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          APP_TAG: ${{ github.event.release.tag_name }}

        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USER_NAME_PRODUCTION }}
          password: ${{ secrets.SSH_PASS }}
          envs: APP_PROD_PATH, GIT_URL, MINIO_PROD_ENDPOINT, MINIO_PROD_ACCESS_KEY, MINIO_PROD_SECRET_KEY, APP_PROD_PORT,DOCKERHUB_USERNAME, DOCKERHUB_TOKEN, APP_TAG
          script: |

            sudo docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN

            if [[ -d "${APP_PROD_PATH}" ]]; then 
              cd "${APP_PROD_PATH}"
              sudo docker compose down pacmusic-prod
              git pull origin master
            else
              ssh-keyscan github.com > ~/.ssh/known_hosts
              git clone "${GIT_URL}" "${APP_PROD_PATH}"
              cd "${APP_PROD_PATH}"
            fi

            echo "DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME}/Pacmusic" > .env
            echo "APP_TAG=$APP_TAG" >> .env
            echo "APP_PROD_PORT=$APP_PROD_PORT" >> .env
            echo "MINIO_PROD_ENDPOINT=$MINIO_PROD_ENDPOINT" >> .env
            echo "MINIO_PROD_ACCESS_KEY=$MINIO_PROD_ACCESS_KEY" >> .env
            echo "MINIO_PROD_SECRET_KEY=${MINIO_PROD_SECRET_KEY}" >> .env
            

            # Run app
            docker compose up --build --detach ${DOCKERHUB_USERNAME}/ pacmusic-prod:${APP_TAG}

      # Step 3: Test Hit Endpoint
      - name: Test endpoint
        run: |
          curl ${{ secrets.PROD_URL }}
